### ISSUE TITLE
composer issues

### ISSUE THREAD

**Issue by liedekef** [simplesamlphp/simplesamlphp-module-aggregator2#11]
Trying to get the module via composer fails for me (dependancy with too old simplesaml?).
Also the www subdir is missing from the dev-tree (it is in release-1.1 branch and in the tags though).

**Comment by tvdijen** [comment]
Hi @liedekef ! v1.1.2 should be working with SimpleSAMLphp 1.19..
The www-directories are going to disappear everywhere since we're migrating to Symfony routing / controller classes.

**Comment by liedekef** [comment]
Hi, I was talking about the dev-version (like the readme indicates on the main page: composer.phar require simplesamlphp/simplesamlphp-module-aggregator2:dev-master ).
But I downloaded the 1.1.3 version which works fine :-)
