### ISSUE TITLE
support for PublicationInfo tag 

### ISSUE THREAD

**Issue by daserzw** [simplesamlphp/simplesamlphp-module-aggregator2#4]
Hi, the new eduGAIN validator requires the <mdrpi:PublicationInfo> tag to be inserted in the SAML Metadata root element as indicated in **https://github.com/REFEDS/SAML-Profile/blob/master/edugain-saml-profile.md**.

Can it be added to the aggregator2 module?

**Comment by tvdijen** [comment]
Hi @daserzw !  I'm not very familiar with this metadata extension, but the change seemed so straight-forward that I just filed a PR for it.. Could you review it and perhaps run a few tests with it?

**Comment by daserzw** [comment]
Hi, thanks a lot! 
I'm currently testing it and it looks promising. Unfortunately I've found another issue with the `RegistrationInfo` element: the eduGAIN SAML profile says that RegistrationInfo MUST be specified _per each_ `EntityDescriptor`. I'll figure out if it is possible to change the eduGAIN SAML profile, or I'll open another Issue :-)

**Comment by tvdijen** [comment]
Again, I'm not familiar with this module and what it does, but looking at the configuration template:

```
     * 'example' will be one set of aggregated metadata.
     * The aggregated metadata can be retrieved from:
```

I think that means that you can configure more that one entity...
Unless you have hundreds of entities, you should be fine.. If too many, we may consider supporting some default values..

**Comment by jpsainea** [comment]
Hi,
How I could add the metadata generated by the module-aggregator2 to the mdrpi-PublicationInfo information? Someone has been able to solve the problem?, I have same problem as @daserzw with Edugain.
