### ISSUE TITLE
Add name attribute to config

### ISSUE THREAD

**Issue by hadamlenz** [simplesamlphp/simplesamlphp-module-aggregator2#6]
adding `'name' => 'Group Name',` to the $config should allow for the naming of the group as defined by `\SAML2\XML\md\EntitiesDescriptor;`

this would require adding the following to SimpleSAML\Module\aggregator2:: __construct()
`$this->name = $config->getString('name', null );`

and the following to SimpleSAML\Module\aggregator2::getEntitiesDescriptor()

```
if( $this->name !== null ){
 $ret->setName( $this->name );
}
```

I can produce a merge request if you like

**Comment by tvdijen** [comment]
Closed in 744ef14
