### ISSUE TITLE
SSP 1.19 Errors

### ISSUE THREAD

**Issue by mirosgold** [simplesamlphp/simplesamlphp-module-aggregator2#7]
Hi, 
Is the latest SSP supported?
I'm  getting errors:

 Error: Cannot access private property SAML2\XML\md\EntitiesDescriptor::$children
Backtrace:
5 modules/aggregator2/lib/Aggregator.php:517 (SimpleSAML\Module\aggregator2\Aggregator::getEntitiesDescriptor)
4 modules/aggregator2/lib/Aggregator.php:696 (SimpleSAML\Module\aggregator2\Aggregator::updateCachedMetadata)
3 modules/aggregator2/lib/Aggregator.php:728 (SimpleSAML\Module\aggregator2\Aggregator::getMetadata)
2 modules/aggregator2/www/get.php:21 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

Thanks

**Comment by tvdijen** [comment]
I'll come up with a new version of this module ASAP

**Comment by mirosgold** [comment]
Thanks!

**Comment by tvdijen** [comment]
@mirosgold Please let me know if v1.1.1 has fixed your issue

**Comment by mirosgold** [comment]
I'll check next week.

**Comment by mirosgold** [comment]
I get:


SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:20 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Error: Call to a member function render() on null
Backtrace:
4 lib/SimpleSAML/XHTML/Template.php:524 (SimpleSAML\XHTML\Template::getContents)
3 lib/SimpleSAML/XHTML/Template.php:541 (SimpleSAML\XHTML\Template::send)
2 modules/aggregator2/www/index.php:36 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by tvdijen** [comment]
Should be taken care of in v1.1.2

**Comment by mirosgold** [comment]
Thank!
Looks like it's working.

**Comment by tvdijen** [comment]
Thanks for testing! If you run into something, let me know!
